# Generated by Django 3.1.5 on 2021-07-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounte', '0003_auto_20210718_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
